apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app: django
data:
  SECRET_KEY: "empty"
  DATABASE_URL: "postgres://test_k8s:OwOtBep9Frut@172.20.10.2:5432/test_k8s"
  ALLOWED_HOSTS: "*"
  DEBUG: "True"
