apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-container
        image: k8s-test-django:latest
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
            name: django-config
          - secretRef:
            name: django-secret
        ports:
        - containerPort: 80
