apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  SECRET_KEY: <DJANGO-SECRET_KEY>
  DATABASE_URL: <postgres://user:password@host:port/db_name>
  ALLOWED_HOSTS: ""
