apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 */1 * *"
  startingDeadlineSeconds: 20
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          containers:
            - name: django-clearsessions
              image: k8s-test-django:latest
              imagePullPolicy: Never
              command: ["python", "manage.py", "clearsessions"]
              ports:
                - containerPort: 80
              envFrom:
              - configMapRef:
                name: django-config
              - secretRef:
                name: django-secrets
          restartPolicy: OnFailure
